//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablaISR
    {
        public int id { get; set; }
        public Nullable<decimal> LimInf { get; set; }
        public Nullable<decimal> LimSup { get; set; }
        public Nullable<decimal> CuotaFija { get; set; }
        public Nullable<decimal> ExedLimInf { get; set; }
        public Nullable<decimal> Subsidio { get; set; }
    }
}
